"""
src/bot/github_bot.py

Posts inline review comments on GitHub PRs using PyGithub.
"""

from __future__ import annotations

import os
from typing import Optional

from github import Github, GithubException
from loguru import logger

from src.model.inference import InferenceResult


class GitHubBot:
    """
    Posts code review findings as inline comments on GitHub PRs.

    Usage:
        bot = GitHubBot()
        await bot.post_review_comments(repo, pr_number, results)
    """

    def __init__(self, token: Optional[str] = None):
        self._token = token or os.getenv("GITHUB_TOKEN", "")
        self._gh    = Github(self._token) if self._token else None

    async def post_review_comments(
        self,
        repo_name:  str,
        pr_number:  int,
        results:    list[InferenceResult],
        commit_sha: Optional[str] = None,
    ) -> int:
        """
        Post actionable findings as a single PR review with inline comments.

        Returns number of comments posted.
        """
        if not self._gh:
            logger.warning("No GITHUB_TOKEN — skipping comment posting")
            return 0

        try:
            repo = self._gh.get_repo(repo_name)
            pr   = repo.get_pull(pr_number)
            sha  = commit_sha or pr.head.sha

            # Build review comments list
            comments = []
            for result in results:
                for finding in result.actionable_findings:
                    comments.append({
                        "path":     finding.hunk_file,
                        "position": finding.line_start,
                        "body":     finding.to_comment(),
                    })

            if not comments:
                # Post a clean bill of health
                pr.create_review(
                    commit=repo.get_commit(sha),
                    body=(
                        "✅ **CodeReviewBot**: No anti-patterns or security issues detected "
                        "in this PR. Looks clean!"
                    ),
                    event="COMMENT",
                )
                logger.info(f"PR#{pr_number}: posted clean review")
                return 0

            # Post as a single review with all inline comments
            pr.create_review(
                commit=repo.get_commit(sha),
                body=self._summary_body(results),
                event="COMMENT",
                comments=comments,
            )

            logger.info(f"PR#{pr_number}: posted {len(comments)} inline comment(s)")
            return len(comments)

        except GithubException as e:
            logger.error(f"GitHub API error on PR#{pr_number}: {e}")
            return 0

    def _summary_body(self, results: list[InferenceResult]) -> str:
        """Build the top-level review summary comment."""
        all_findings = [f for r in results for f in r.actionable_findings]
        critical = [f for f in all_findings if f.severity == "critical"]
        high     = [f for f in all_findings if f.severity == "high"]
        medium   = [f for f in all_findings if f.severity == "medium"]
        low      = [f for f in all_findings if f.severity == "low"]

        lines = [
            "## 🤖 CodeReviewBot — Automated First-Pass Review\n",
            f"Found **{len(all_findings)}** issue(s) across **{len(results)}** hunk(s).\n",
            "| Severity | Count |",
            "|----------|-------|",
        ]
        if critical: lines.append(f"| 🔴 Critical | {len(critical)} |")
        if high:     lines.append(f"| 🟠 High     | {len(high)} |")
        if medium:   lines.append(f"| 🟡 Medium   | {len(medium)} |")
        if low:      lines.append(f"| 🔵 Low      | {len(low)} |")

        lines.append(
            "\n> _This review was generated by a fine-tuned CodeLlama-7B model. "
            "Always verify findings before acting on them._"
        )
        return "\n".join(lines)
